### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by genodeftest** [pygobject/pgi-docs-devhelp#3]
Now that GNOME 3.24 has been released, can you please update this repo? Or is there a script to do it myself and create a pull request?

**Comment by lazka** [comment]
Will do.

I'm following Debian, so that's the best I can do atm: https://www.0d.be/debian/debian-gnome-3.24-status.html

**Comment by lazka** [comment]
(regarding the script, this is used: https://github.com/pygobject/pgi-docgen/blob/master/tools/build-debian.py but it takes 1-2 hours and requires debian sid)

**Comment by lazka** [comment]
Pushed an update.

**Comment by genodeftest** [comment]
Thanks!
